import type { FormEvent } from "react";
import type { AuthResponse } from "../../api/auth";
import type { OwnerTrip, SharedFlight, SharedPlace, SharedSchedule } from "../../api/trips";
import type { FlightDirection } from "../../shared/travelOptions";
import type { PlaceCategory, ScheduleItem } from "../../types/travel";

export type AuthMode = "login" | "register";

// useTripManageController가 계산한 여행 관리 화면 입력값과 이벤트 핸들러를 한 번에 전달한다.
export type TripManagePageProps = {
  auth: AuthResponse | null;
  authChecked: boolean;
  authEmail: string;
  authError: string;
  authMode: AuthMode;
  authPassword: string;
  authSubmitting: boolean;
  newTripEndDate: string;
  newTripMemo: string;
  newTripStartDate: string;
  newTripTitle: string;
  newTripTravelers: string;
  newScheduleDate: string;
  newScheduleGuideMemo: string;
  newSchedulePlaceID: string;
  newScheduleTime: string;
  newScheduleTitle: string;
  newScheduleTransportMemo: string;
  newScheduleType: ScheduleItem["type"];
  newPlaceAddress: string;
  newPlaceCategory: PlaceCategory;
  newPlaceGoogleMapsURL: string;
  newPlaceName: string;
  newPlaceRecommendedReason: string;
  newFlightAirline: string;
  newFlightArrivalAirport: string;
  newFlightArrivalDate: string;
  newFlightArrivalTime: string;
  newFlightDepartureAirport: string;
  newFlightDepartureDate: string;
  newFlightDepartureTime: string;
  newFlightDirection: FlightDirection;
  newFlightLabel: string;
  newFlightMemo: string;
  newFlightNumber: string;
  ownerTrips: OwnerTrip[];
  ownerTripsError: string;
  ownerTripsLoading: boolean;
  ownerSchedules: SharedSchedule[];
  ownerPlaces: SharedPlace[];
  ownerFlights: SharedFlight[];
  ownerDetailDataError: string;
  ownerDetailDataLoading: boolean;
  isScheduleListEditing: boolean;
  deletingScheduleID: string;
  isPlaceListEditing: boolean;
  deletingPlaceID: string;
  selectedOwnerTrip: OwnerTrip | null;
  selectedShareLink: string;
  flightCreateError: string;
  flightCreateSubmitting: boolean;
  placeCreateError: string;
  placeCreateSubmitting: boolean;
  placeDeleteError: string;
  scheduleCreateError: string;
  scheduleCreateSubmitting: boolean;
  scheduleDeleteError: string;
  shareLinkCopied: boolean;
  shareLinkError: string;
  shareLinkSubmitting: boolean;
  tripCreateError: string;
  tripCreateSubmitting: boolean;
  tripEditEndDate: string;
  tripEditError: string;
  tripEditMemo: string;
  tripEditStartDate: string;
  tripEditSubmitting: boolean;
  tripEditTitle: string;
  tripEditTravelers: string;
  onAuthEmailChange: (value: string) => void;
  onAuthModeChange: (mode: AuthMode) => void;
  onAuthPasswordChange: (value: string) => void;
  onNewTripEndDateChange: (value: string) => void;
  onNewTripMemoChange: (value: string) => void;
  onNewTripStartDateChange: (value: string) => void;
  onNewTripTitleChange: (value: string) => void;
  onNewTripTravelersChange: (value: string) => void;
  onNewScheduleDateChange: (value: string) => void;
  onNewScheduleGuideMemoChange: (value: string) => void;
  onNewSchedulePlaceIDChange: (value: string) => void;
  onNewScheduleTimeChange: (value: string) => void;
  onNewScheduleTitleChange: (value: string) => void;
  onNewScheduleTransportMemoChange: (value: string) => void;
  onNewScheduleTypeChange: (value: ScheduleItem["type"]) => void;
  onNewPlaceAddressChange: (value: string) => void;
  onNewPlaceCategoryChange: (value: PlaceCategory) => void;
  onNewPlaceGoogleMapsURLChange: (value: string) => void;
  onNewPlaceNameChange: (value: string) => void;
  onNewPlaceRecommendedReasonChange: (value: string) => void;
  onNewFlightAirlineChange: (value: string) => void;
  onNewFlightArrivalAirportChange: (value: string) => void;
  onNewFlightArrivalDateChange: (value: string) => void;
  onNewFlightArrivalTimeChange: (value: string) => void;
  onNewFlightDepartureAirportChange: (value: string) => void;
  onNewFlightDepartureDateChange: (value: string) => void;
  onNewFlightDepartureTimeChange: (value: string) => void;
  onNewFlightDirectionChange: (value: FlightDirection) => void;
  onNewFlightLabelChange: (value: string) => void;
  onNewFlightMemoChange: (value: string) => void;
  onNewFlightNumberChange: (value: string) => void;
  onCloseOwnerTripDetail: () => void;
  onCopyShareLink: () => void;
  onCreateShareLink: () => void;
  onDeleteSchedule: (scheduleID: string) => void;
  onScheduleListEditingChange: (value: boolean) => void;
  onDeletePlace: (placeID: string) => void;
  onPlaceListEditingChange: (value: boolean) => void;
  onTripEditEndDateChange: (value: string) => void;
  onTripEditMemoChange: (value: string) => void;
  onTripEditStartDateChange: (value: string) => void;
  onTripEditTitleChange: (value: string) => void;
  onTripEditTravelersChange: (value: string) => void;
  onLogout: () => void;
  onSelectOwnerTrip: (tripID: string) => void;
  onSubmitAuth: (event: FormEvent<HTMLFormElement>) => void;
  onSubmitNewFlight: (event: FormEvent<HTMLFormElement>) => void;
  onSubmitNewPlace: (event: FormEvent<HTMLFormElement>) => void;
  onSubmitNewTrip: (event: FormEvent<HTMLFormElement>) => void;
  onSubmitNewSchedule: (event: FormEvent<HTMLFormElement>) => void;
  onSubmitTripEdit: (event: FormEvent<HTMLFormElement>) => void;
};
