import { syncStartDateWithEndDate } from "./manageFormUtils";
import type { TripManagePageProps } from "./manageTypes";
import { useSelectedOwnerTripLifecycle } from "./useSelectedOwnerTripLifecycle";
import { useTripManageDetailData } from "./useTripManageDetailData";
import {
  useFlightManageFormState,
  usePlaceManageFormState,
  useScheduleManageFormState,
  useTripCreateFormState,
  useTripEditFormState,
} from "./useTripManageFormState";
import { useTripManageSessionTrips } from "./useTripManageSessionTrips";
import { useTripManageShareLink } from "./useTripManageShareLink";

type UseTripManageControllerParams = {
  currentPath: string;
  isLegacyOwnerRoute: boolean;
  isManageRoute: boolean;
};

// 여행 관리 화면의 인증, 서버 데이터 조회, 생성/삭제 핸들러를 TripManagePage props로 변환한다.
export function useTripManageController({
  currentPath,
  isLegacyOwnerRoute,
  isManageRoute,
}: UseTripManageControllerParams): TripManagePageProps {
  // 여행 생성/수정 입력 상태는 화면 상태만 담당하고, API 요청은 세션 훅에서 처리한다.
  const {
    newTripTitle,
    setNewTripTitle,
    newTripStartDate,
    setNewTripStartDate,
    newTripEndDate,
    setNewTripEndDate,
    newTripTravelers,
    setNewTripTravelers,
    newTripMemo,
    setNewTripMemo,
    tripCreateError,
    setTripCreateError,
    tripCreateSubmitting,
    setTripCreateSubmitting,
    resetTripCreateForm,
  } = useTripCreateFormState();
  const {
    tripEditTitle,
    setTripEditTitle,
    tripEditStartDate,
    setTripEditStartDate,
    tripEditEndDate,
    setTripEditEndDate,
    tripEditTravelers,
    setTripEditTravelers,
    tripEditMemo,
    setTripEditMemo,
    tripEditError,
    setTripEditError,
    tripEditSubmitting,
    setTripEditSubmitting,
    resetTripEditForm,
    fillTripEditForm,
  } = useTripEditFormState();
  // 인증 세션과 여행 목록은 상세 리소스보다 상위 개념이라 별도 훅에서 먼저 구성한다.
  const {
    authChecked,
    authEmail,
    authError,
    authMode,
    authPassword,
    authSubmitting,
    changeAuthMode,
    clearOwnerSessionBase,
    ownerAuth,
    ownerTrips,
    ownerTripsError,
    ownerTripsLoading,
    resetSessionMessagesForLogout,
    selectedOwnerTrip,
    setAuthEmail,
    setAuthPassword,
    setSelectedOwnerTripID,
    submitAuth,
    submitNewTrip,
    submitTripEdit,
  } = useTripManageSessionTrips({
    currentPath,
    isLegacyOwnerRoute,
    isManageRoute,
    tripCreateForm: {
      newTripEndDate,
      newTripMemo,
      newTripStartDate,
      newTripTitle,
      newTripTravelers,
      resetTripCreateForm,
      setTripCreateError,
      setTripCreateSubmitting,
    },
    tripEditForm: {
      setTripEditError,
      setTripEditSubmitting,
      tripEditEndDate,
      tripEditMemo,
      tripEditStartDate,
      tripEditTitle,
      tripEditTravelers,
    },
  });
  // 선택 여행 안쪽의 일정/장소/항공편 폼 상태는 리소스별로 분리해 화면 섹션과 맞춘다.
  const {
    newScheduleDate,
    setNewScheduleDate,
    newScheduleTime,
    setNewScheduleTime,
    newScheduleType,
    setNewScheduleType,
    newScheduleTitle,
    setNewScheduleTitle,
    newSchedulePlaceID,
    setNewSchedulePlaceID,
    newScheduleTransportMemo,
    setNewScheduleTransportMemo,
    newScheduleGuideMemo,
    setNewScheduleGuideMemo,
    scheduleCreateError,
    setScheduleCreateError,
    scheduleCreateSubmitting,
    setScheduleCreateSubmitting,
    isScheduleListEditing,
    setIsScheduleListEditing,
    scheduleDeleteError,
    setScheduleDeleteError,
    deletingScheduleID,
    setDeletingScheduleID,
    editingScheduleID,
    editingScheduleDate,
    setEditingScheduleDate,
    editingScheduleTime,
    setEditingScheduleTime,
    editingScheduleType,
    setEditingScheduleType,
    editingScheduleTitle,
    setEditingScheduleTitle,
    editingSchedulePlaceID,
    setEditingSchedulePlaceID,
    editingScheduleTransportMemo,
    setEditingScheduleTransportMemo,
    editingScheduleGuideMemo,
    setEditingScheduleGuideMemo,
    scheduleEditError,
    setScheduleEditError,
    scheduleEditSubmitting,
    setScheduleEditSubmitting,
    cancelScheduleEdit,
    startScheduleEdit,
    resetScheduleManageForm,
    prepareScheduleManageForm,
  } = useScheduleManageFormState();
  const {
    newPlaceName,
    setNewPlaceName,
    newPlaceCategory,
    setNewPlaceCategory,
    newPlaceAddress,
    setNewPlaceAddress,
    newPlaceGoogleMapsURL,
    setNewPlaceGoogleMapsURL,
    newPlaceRecommendedReason,
    setNewPlaceRecommendedReason,
    placeCreateError,
    setPlaceCreateError,
    placeCreateSubmitting,
    setPlaceCreateSubmitting,
    isPlaceListEditing,
    setIsPlaceListEditing,
    placeDeleteError,
    setPlaceDeleteError,
    deletingPlaceID,
    setDeletingPlaceID,
    editingPlaceID,
    editingPlaceName,
    setEditingPlaceName,
    editingPlaceCategory,
    setEditingPlaceCategory,
    editingPlaceAddress,
    setEditingPlaceAddress,
    editingPlaceGoogleMapsURL,
    setEditingPlaceGoogleMapsURL,
    editingPlaceRecommendedReason,
    setEditingPlaceRecommendedReason,
    placeEditError,
    setPlaceEditError,
    placeEditSubmitting,
    setPlaceEditSubmitting,
    cancelPlaceEdit,
    startPlaceEdit,
    resetPlaceManageForm,
  } = usePlaceManageFormState();
  const {
    newFlightDirection,
    setNewFlightDirection,
    newFlightLabel,
    setNewFlightLabel,
    newFlightAirline,
    setNewFlightAirline,
    newFlightNumber,
    setNewFlightNumber,
    newFlightDepartureAirport,
    setNewFlightDepartureAirport,
    newFlightArrivalAirport,
    setNewFlightArrivalAirport,
    newFlightDepartureDate,
    setNewFlightDepartureDate,
    newFlightDepartureTime,
    setNewFlightDepartureTime,
    newFlightArrivalDate,
    setNewFlightArrivalDate,
    newFlightArrivalTime,
    setNewFlightArrivalTime,
    newFlightMemo,
    setNewFlightMemo,
    flightCreateError,
    setFlightCreateError,
    flightCreateSubmitting,
    setFlightCreateSubmitting,
    resetFlightManageForm,
    prepareFlightManageForm,
  } = useFlightManageFormState();

  // 인증이 만료되었을 때 화면에 남은 소유자 전용 상세 데이터까지 한 번에 비운다.
  function clearOwnerSession() {
    clearOwnerSessionBase();
    clearOwnerDetailData();
  }

  const {
    clearOwnerDetailData,
    deleteOwnerPlace,
    deleteOwnerSchedule,
    ownerDetailDataError,
    ownerDetailDataLoading,
    ownerFlights,
    ownerPlaces,
    ownerSchedules,
    submitNewFlight,
    submitNewPlace,
    submitNewSchedule,
    submitPlaceEdit,
    submitScheduleEdit,
  } = useTripManageDetailData({
    clearOwnerSession,
    ownerAuth,
    selectedOwnerTrip,
    scheduleForm: {
      newScheduleDate,
      newScheduleGuideMemo,
      newSchedulePlaceID,
      newScheduleTime,
      newScheduleTitle,
      newScheduleTransportMemo,
      newScheduleType,
      cancelScheduleEdit,
      editingScheduleDate,
      editingScheduleGuideMemo,
      editingScheduleID,
      editingSchedulePlaceID,
      editingScheduleTime,
      editingScheduleTitle,
      editingScheduleTransportMemo,
      editingScheduleType,
      setDeletingScheduleID,
      setNewScheduleGuideMemo,
      setNewSchedulePlaceID,
      setNewScheduleTime,
      setNewScheduleTitle,
      setNewScheduleTransportMemo,
      setScheduleCreateError,
      setScheduleCreateSubmitting,
      setScheduleDeleteError,
      setScheduleEditError,
      setScheduleEditSubmitting,
    },
    placeForm: {
      newPlaceAddress,
      newPlaceCategory,
      newPlaceGoogleMapsURL,
      newPlaceName,
      newPlaceRecommendedReason,
      cancelPlaceEdit,
      editingPlaceAddress,
      editingPlaceCategory,
      editingPlaceGoogleMapsURL,
      editingPlaceID,
      editingPlaceName,
      editingPlaceRecommendedReason,
      setDeletingPlaceID,
      setPlaceEditError,
      setPlaceEditSubmitting,
      setNewPlaceAddress,
      setNewPlaceGoogleMapsURL,
      setNewPlaceName,
      setNewPlaceRecommendedReason,
      setNewSchedulePlaceID,
      setPlaceCreateError,
      setPlaceCreateSubmitting,
      setPlaceDeleteError,
    },
    flightForm: {
      newFlightAirline,
      newFlightArrivalAirport,
      newFlightArrivalDate,
      newFlightArrivalTime,
      newFlightDepartureAirport,
      newFlightDepartureDate,
      newFlightDepartureTime,
      newFlightDirection,
      newFlightLabel,
      newFlightMemo,
      newFlightNumber,
      setFlightCreateError,
      setFlightCreateSubmitting,
      setNewFlightAirline,
      setNewFlightArrivalAirport,
      setNewFlightArrivalTime,
      setNewFlightDepartureAirport,
      setNewFlightDepartureTime,
      setNewFlightLabel,
      setNewFlightMemo,
      setNewFlightNumber,
    },
  });
  // 공유 링크는 선택 여행과 인증 토큰만 알면 되므로 상세 데이터 조회 훅과 분리한다.
  const {
    copySelectedTripShareLink,
    createSelectedTripShareLink,
    resetShareLinkState,
    selectedShareLink,
    shareLinkCopied,
    shareLinkError,
    shareLinkSubmitting,
  } = useTripManageShareLink({
    clearOwnerSession,
    ownerAuth,
    selectedOwnerTrip,
  });

  useSelectedOwnerTripLifecycle({
    fillTripEditForm,
    prepareFlightManageForm,
    prepareScheduleManageForm,
    resetFlightManageForm,
    resetPlaceManageForm,
    resetScheduleManageForm,
    resetTripEditForm,
    selectedOwnerTrip,
  });

  // 로그아웃은 인증뿐 아니라 현재 화면의 pending/submitting 상태까지 초기화해야 재로그인 시 잔상이 남지 않는다.
  function logoutOwner() {
    clearOwnerSession();
    resetShareLinkState();
    setScheduleCreateSubmitting(false);
    resetScheduleManageForm();
    setPlaceCreateSubmitting(false);
    resetPlaceManageForm();
    setFlightCreateSubmitting(false);
    resetFlightManageForm();
    resetSessionMessagesForLogout();
  }

  // 일정 목록 편집을 닫을 때 열려 있던 일정 수정 폼도 함께 닫아 화면 상태를 단순하게 유지한다.
  function changeScheduleListEditing(value: boolean) {
    setIsScheduleListEditing(value);
    if (!value) {
      cancelScheduleEdit();
    }
  }

  // 장소 목록 편집을 닫을 때 열려 있던 장소 수정 폼도 함께 닫아 화면 상태를 단순하게 유지한다.
  function changePlaceListEditing(value: boolean) {
    setIsPlaceListEditing(value);
    if (!value) {
      cancelPlaceEdit();
    }
  }

  // TripManagePage는 순수 화면 컴포넌트라 여기서 모든 상태와 이벤트 핸들러를 props로 조립한다.
  return {
    auth: ownerAuth,
    authChecked,
    authEmail,
    authError,
    authMode,
    authPassword,
    authSubmitting,
    ownerTrips,
    ownerTripsError,
    ownerTripsLoading,
    ownerSchedules,
    ownerPlaces,
    ownerFlights,
    ownerDetailDataError,
    ownerDetailDataLoading,
    isScheduleListEditing,
    deletingScheduleID,
    editingScheduleID,
    editingScheduleDate,
    editingScheduleTime,
    editingScheduleType,
    editingScheduleTitle,
    editingSchedulePlaceID,
    editingScheduleTransportMemo,
    editingScheduleGuideMemo,
    isPlaceListEditing,
    deletingPlaceID,
    editingPlaceID,
    editingPlaceName,
    editingPlaceCategory,
    editingPlaceAddress,
    editingPlaceGoogleMapsURL,
    editingPlaceRecommendedReason,
    selectedOwnerTrip,
    selectedShareLink,
    newTripEndDate,
    newTripMemo,
    newTripStartDate,
    newTripTitle,
    newTripTravelers,
    newScheduleDate,
    newScheduleGuideMemo,
    newSchedulePlaceID,
    newScheduleTime,
    newScheduleTitle,
    newScheduleTransportMemo,
    newScheduleType,
    newPlaceAddress,
    newPlaceCategory,
    newPlaceGoogleMapsURL,
    newPlaceName,
    newPlaceRecommendedReason,
    newFlightAirline,
    newFlightArrivalAirport,
    newFlightArrivalDate,
    newFlightArrivalTime,
    newFlightDepartureAirport,
    newFlightDepartureDate,
    newFlightDepartureTime,
    newFlightDirection,
    newFlightLabel,
    newFlightMemo,
    newFlightNumber,
    flightCreateError,
    flightCreateSubmitting,
    placeCreateError,
    placeCreateSubmitting,
    placeDeleteError,
    placeEditError,
    placeEditSubmitting,
    scheduleCreateError,
    scheduleCreateSubmitting,
    scheduleDeleteError,
    scheduleEditError,
    scheduleEditSubmitting,
    shareLinkCopied,
    shareLinkError,
    shareLinkSubmitting,
    tripCreateError,
    tripCreateSubmitting,
    tripEditEndDate,
    tripEditError,
    tripEditMemo,
    tripEditStartDate,
    tripEditSubmitting,
    tripEditTitle,
    tripEditTravelers,
    onAuthEmailChange: setAuthEmail,
    onAuthModeChange: changeAuthMode,
    onAuthPasswordChange: setAuthPassword,
    onNewTripEndDateChange: setNewTripEndDate,
    onNewTripMemoChange: setNewTripMemo,
    onNewTripStartDateChange: (value) =>
      syncStartDateWithEndDate(value, newTripEndDate, setNewTripStartDate, setNewTripEndDate),
    onNewTripTitleChange: setNewTripTitle,
    onNewTripTravelersChange: setNewTripTravelers,
    onNewScheduleDateChange: setNewScheduleDate,
    onNewScheduleGuideMemoChange: setNewScheduleGuideMemo,
    onNewSchedulePlaceIDChange: setNewSchedulePlaceID,
    onNewScheduleTimeChange: setNewScheduleTime,
    onNewScheduleTitleChange: setNewScheduleTitle,
    onNewScheduleTransportMemoChange: setNewScheduleTransportMemo,
    onNewScheduleTypeChange: setNewScheduleType,
    onEditingScheduleDateChange: setEditingScheduleDate,
    onEditingScheduleGuideMemoChange: setEditingScheduleGuideMemo,
    onEditingSchedulePlaceIDChange: setEditingSchedulePlaceID,
    onEditingScheduleTimeChange: setEditingScheduleTime,
    onEditingScheduleTitleChange: setEditingScheduleTitle,
    onEditingScheduleTransportMemoChange: setEditingScheduleTransportMemo,
    onEditingScheduleTypeChange: setEditingScheduleType,
    onEditingPlaceAddressChange: setEditingPlaceAddress,
    onEditingPlaceCategoryChange: setEditingPlaceCategory,
    onEditingPlaceGoogleMapsURLChange: setEditingPlaceGoogleMapsURL,
    onEditingPlaceNameChange: setEditingPlaceName,
    onEditingPlaceRecommendedReasonChange: setEditingPlaceRecommendedReason,
    onNewPlaceAddressChange: setNewPlaceAddress,
    onNewPlaceCategoryChange: setNewPlaceCategory,
    onNewPlaceGoogleMapsURLChange: setNewPlaceGoogleMapsURL,
    onNewPlaceNameChange: setNewPlaceName,
    onNewPlaceRecommendedReasonChange: setNewPlaceRecommendedReason,
    onNewFlightAirlineChange: setNewFlightAirline,
    onNewFlightArrivalAirportChange: setNewFlightArrivalAirport,
    onNewFlightArrivalDateChange: setNewFlightArrivalDate,
    onNewFlightArrivalTimeChange: setNewFlightArrivalTime,
    onNewFlightDepartureAirportChange: setNewFlightDepartureAirport,
    onNewFlightDepartureDateChange: (value) =>
      syncStartDateWithEndDate(value, newFlightArrivalDate, setNewFlightDepartureDate, setNewFlightArrivalDate),
    onNewFlightDepartureTimeChange: setNewFlightDepartureTime,
    onNewFlightDirectionChange: setNewFlightDirection,
    onNewFlightLabelChange: setNewFlightLabel,
    onNewFlightMemoChange: setNewFlightMemo,
    onNewFlightNumberChange: setNewFlightNumber,
    onCloseOwnerTripDetail: () => setSelectedOwnerTripID(null),
    onCopyShareLink: copySelectedTripShareLink,
    onCreateShareLink: createSelectedTripShareLink,
    onCancelPlaceEdit: cancelPlaceEdit,
    onCancelScheduleEdit: cancelScheduleEdit,
    onDeleteSchedule: deleteOwnerSchedule,
    onScheduleListEditingChange: changeScheduleListEditing,
    onStartScheduleEdit: startScheduleEdit,
    onDeletePlace: deleteOwnerPlace,
    onPlaceListEditingChange: changePlaceListEditing,
    onStartPlaceEdit: startPlaceEdit,
    onTripEditEndDateChange: setTripEditEndDate,
    onTripEditMemoChange: setTripEditMemo,
    onTripEditStartDateChange: (value) =>
      syncStartDateWithEndDate(value, tripEditEndDate, setTripEditStartDate, setTripEditEndDate),
    onTripEditTitleChange: setTripEditTitle,
    onTripEditTravelersChange: setTripEditTravelers,
    onLogout: logoutOwner,
    onSelectOwnerTrip: setSelectedOwnerTripID,
    onSubmitAuth: submitAuth,
    onSubmitNewPlace: submitNewPlace,
    onSubmitNewFlight: submitNewFlight,
    onSubmitNewTrip: submitNewTrip,
    onSubmitNewSchedule: submitNewSchedule,
    onSubmitPlaceEdit: submitPlaceEdit,
    onSubmitScheduleEdit: submitScheduleEdit,
    onSubmitTripEdit: submitTripEdit,
  };
}
